### ISSUE TITLE
Unable to Edit Calendar Events

### ISSUE THREAD

**Issue by Christoqh** [fengoffice/fengoffice#114]
Calendar events are one of the most crucial modules for us, making this a critical issue — whether it's on my end or with Feng Office. I've already tried accessing it through various browsers (Chrome, Firefox, etc.). 
My question is: Am I the only one unable to edit events? 

Description: 
- Feng Office version: 3.11.4.14
- PHP version: 8.3

This issue is specific to event editing and does not affect tasks or other features. Adding events works fine, but when I attempt to edit an event and click "Save changes," a brief "Loading" message appears, yet the changes are not applied, and the popup edit window remains open. This issue resembles the circumstances described here: https://github.com/fengoffice/fengoffice/issues/50

**Comment by sgrimmett** [comment]
We see this as well, I believe it's related to permissions as we also see similar behaviour where nothing happens, and no errors logged when adding / Changing permissions in a workspace as well.

We see this in php8, but not if we revert back to php7.4.

We are also unable to upload docx files on php8 for some reason.  

As of now - we've had to revert to running on php7.4 for server functionality.

@Christoqh do you see this behaviour when adding/changing permissions in a workspace?  Are you able to upload docx files?

**Comment by Christoqh** [comment]
Same thing here... @sgrimmett 
I am experiencing the same issues with:

- non-uploadable DOCX files and
- failed adding/changing permissions in a workspace.

This is quite frustrating.

**Comment by sgrimmett** [comment]
@ces27 @alvarotm01 Issues in php8 related to docx files uploading and permissions (specifically adding/changing permissions in a workspace, or editing a calendar event).

**Comment by sgrimmett** [comment]
I just tried upgrading to 3.11.5.0-rc2 to ensure the behaviour was the same - no difference between 3.11.5.0-rc2 and 3.11.4.14

**Comment by Christoqh** [comment]
@sgrimmett Our first test with 3.11.6.6 did not work at all. Have you had different experiences?

**Comment by sgrimmett** [comment]
@Christoqh I reviewed the changelog and source code changes, and I didn't expect any changes.

Docx files fail still, and permissions still not being updated, despite a message saying they saved.  No error thrown on permissions.  This is the error on docx upload:

Session "default" started at 2025-02-13T15:20:45+0000
#1 DEBUG: Error when uploading file: Non-static method DOMDocument::loadXML() cannot be called statically
    #0 /application/functions.php(1810): readZippedXML()
    #1 /application/models/ApplicationDataObject.class.php(126): docx2text()
    #2 /application/models/ApplicationDataObject.class.php(205): ApplicationDataObject->addToSearchableObjects()
    #3 /application/models/ContentDataObject.class.php(673): ApplicationDataObject->save()
    #4 /application/models/project_files/ProjectFile.class.php(394): ContentDataObject->save()
    #5 /application/controllers/FilesController.class.php(655): ProjectFile->handleUploadedFile()
    #6 /application/controllers/FilesController.class.php(770): FilesController->add_file_from_multi()
    #7 /environment/classes/controller/Controller.class.php(76): FilesController->add_multiple_files()
    #8 /environment/classes/controller/PageController.class.php(62): Controller->execute()
    #9 /environment/classes/Env.class.php(133): PageController->execute()
    #10 /init.php(179): Env::executeAction()
    #11 /index.php(7): require('...')
    #12 {main}
Time since start: 0.39411807060242 seconds



![Image](https://github.com/user-attachments/assets/e099e2fd-57b5-4868-aa3c-cbde472b7e3c)

**Comment by nico-lois** [comment]
Hello! We just released the 3.11.6.8 CE version! in which this issue is solved. Feel free to download it. Thank you for your time and for reporting this issue to us. IS MUCH APPRITIATED!

**Comment by sgrimmett** [comment]
@nico-lois Thanks for working on this. 

I confirm that editing calendar events now functions and is fixed.  

However, these issues remain:

non-uploadable DOCX files and
failed adding/changing permissions in a workspace.

**Comment by nico-lois** [comment]
Hello! ok we will look into this as soon as possible!

**Comment by nico-lois** [comment]
Hello! we fix the docx uploading problem. We will release the CE with this fix in the upcoming days. On the other hand, I couldn't reproduce any issue regarding permissions on workspaces. If you want we can give me a step by step guide to reproduce this issue.

Here there are 3 different configuration permissions for an Executive user.

<img width="993" alt="Image" src="https://github.com/user-attachments/assets/4bb0f39f-8836-428c-8fd4-b4a0cba265f0" />

<img width="1121" alt="Image" src="https://github.com/user-attachments/assets/4ea8f7a0-b7ae-41bb-9d17-4a463ce57753" />

<img width="661" alt="Image" src="https://github.com/user-attachments/assets/17c3fcb6-71e3-463a-832a-bdae90847863" />

And here the action that the user can perform on these 3 tasks.

<img width="1507" alt="Image" src="https://github.com/user-attachments/assets/d54e9a8b-a94a-4792-befb-e1c93b7b1521" />
<img width="1499" alt="Image" src="https://github.com/user-attachments/assets/e62ce524-d0c3-4dd7-99d9-36192dcfd551" />
<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/66fe0965-9c26-42ff-930e-2641fa712168" />

**Comment by nico-lois** [comment]
You can see the different possibilities on the Actions menu (right-up corner)

**Comment by nico-lois** [comment]
The latest Version is abavilable with the upload problem for docx documents solved
